AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation template for a VPC and associated resources
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.3.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Three-Tier-VPC
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.3.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Three-Tier-Public-Subnet-1
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties: 